Utils Class Update
PekinSOFT-Systems/LoadMaster pull request #68
Opened 2020-10-25 21:05 UTC by SeanCarrick

Since we are attempting to build a professional, high-quality, integrated load tracking and accounting system for owner/operator truck drivers, I have updated the `com.pekinsoft.loadmaster.utils.Utils` class to help us achieve this end.

As we all know, each operating system has a standard for where on the system applications are supposed to store data, preferences, and log files. For this reason, I have added the following four (4) classes to the `Utils` class:

- `getApplicationFolderByOS`: checks the operating system name from the Java VM and returns a string of the path where that OS prefers applications to store their custom files.
- `getApplicationDataFolderByOS`: checks the operating system name from the Java VM and returns a string of the path where that OS prefers application to store their data files.
- `getApplicationSettingsLocationByOS`: checks the operating system name from the Java VM and returns a string of the path where that OS prefers applications to store their settings and configuration files.
- `getSystemLogLocationByOS`: checks the operating system name from the Java VM and returns a string of the path where that OS prefers applications to place their log files.

With this in mind, if we truly want a polished, professional application, we will need to update our code that sets up our folder structure and `AppLogger` class. Using these methods, we can place all of our Load Master™-generated files in the appropriate location for the system on which the user is running it.

@jkovalsky, if you approve of this, please just merge this branch to master. Otherwise, feel free to delete this branch and close the PR without merging. Thank you.

-SC
Signed-off-by:sean <sean@laptop.pekinsoft.com>
Signed-off-by:Sean Carrick <sean@pekinsoft.com>

2020-10-31 20:50 UTC, jkovalsky approved these changes
I suggest to either incorporate my simplifications or rather go with pull request #66 .

2020-10-31 20:50 UTC, jkovalsky commented on Load Master/src/com/pekinsoft/loadmaster/utils/Utils.java
> +        String location = "";
Method can be simplified to:

        String location = "";
        String userHome = System.getProperty("user.home");
        if (osName.toLowerCase().contains("win")) {
            location = "AppData\\LoadMaster";
        } else if (osName.toLowerCase().contains("mac")) {
            location = "Library/Preferences/LoadMaster";
        } else {
            location = ".loadmaster";
        }
        return userHome + File.separator + location + File.separator;

2020-10-31 20:50 UTC, jkovalsky commented on Load Master/src/com/pekinsoft/loadmaster/utils/Utils.java
> +        String location = "";
Using my suggestion above this method can be simplified to:

        String applicationFolder = getApplicationFolderByOS(osName);
        if (osName.toLowerCase().contains("mac")) {
            applicationFolder = System.getProperty("user.home") + "/Library/Application Data/LoadMaster/";
        }
        return applicationFolder + "data" + File.separator;

2020-10-31 20:50 UTC, jkovalsky commented on Load Master/src/com/pekinsoft/loadmaster/utils/Utils.java
> +        String location = "";
Using my suggestion above this method can be simplified to:

        String settingsLocationFolder = getApplicationFolderByOS(osName);
        if (osName.toLowerCase().contains("win")) {
            settingsLocationFolder = settingsLocationFolder + "LoadMaster.cnf";
        } else if (osName.toLowerCase().contains("mac")) {
            settingsLocationFolder = settingsLocationFolder + "LoadMaster.pref";
        } else {
            settingsLocationFolder = settingsLocationFolder + "loadmaster.conf";
        }
        return settingsLocationFolder;

2020-11-04 20:55 UTC, jkovalsky requested changes
Please consider my suggestions or at least reply to my comments. Thank you.

2020-11-21 14:53 UTC, SeanCarrick commented
I am just closing this PR since it has failed all Travis checks. I will redo this PR taking your suggestions and possibly improving upon them.

-SC

2020-11-21 14:53 UTC, closed without merging